### ISSUE TITLE
Disconnect/reconnect getting multiple copies of data

### ISSUE THREAD

**Issue by lxman** [Job79/EasyTcp#10]
So I have set up my client with a connect and disconnect method. I have my server set up to transmit two sets of data (strings) whenever a client connects.
When I connect the first time, it works as expected. However, if I disconnect, then reconnect I get two copies of each message coming into the client.
Debugging through shows that I am only asking the server to transmit the two pieces of information on this reconnect.
So why am I receiving four when I reconnect?
If I disconnect/reconnect again I get six, and so on and so on.

**Comment by Job79** [comment]
Can you share some code to reproduce the issue?

**Comment by Job79** [comment]
Can not reproduce, closing issue for now
