### ISSUE TITLE
Start Function does not Exist in EasyTcpServer()

### ISSUE THREAD

**Issue by bnaambo** [Job79/EasyTcp#39]
The Start Function does not Exist in EasyTcpServer()

**Comment by Job79** [comment]
Hello @bnaambo,

Did you import the namespace 'EasyTcp3.Server.ServerUtils' ?
This namespace contains all the helper functions for the server.

Here is a working example:
```cs
using System.Threading.Tasks;
using EasyTcp3.Server; 
using EasyTcp3.Server.ServerUtils; 

namespace Test
{
    class Program
    {
        static void Main()
        {
            ushort port = 1024;
            using var server = new EasyTcpServer();
            server.Start(port);
            Task.Delay(-1).Wait();
        }
    }
}
```

See also the [basic examples](https://github.com/Job79/EasyTcp/tree/master/EasyTcp3/EasyTcp3.Examples/Basic)

**Comment by bnaambo** [comment]
Oh Got it sorry my fault! Works Perfectly now Thanks
