### ISSUE TITLE
2 bytes missing in Server_OnDataReceive

### ISSUE THREAD

**Issue by ZigmundL** [Job79/EasyTcp#44]
```
static void Main(string[] args)
{
       EasyTcpServer server = new EasyTcpServer();
       server.OnDataReceive += Server_OnDataReceive;
       server.Start(8080);
            
       while (true)
       {
           System.Threading.Thread.Sleep(100);
       }
}

private static void Server_OnDataReceive(object sender, EasyTcp3.Message e)
{
      string request = Encoding.ASCII.GetString(e.Data, 0, e.Data.Length);
      string req = e.ToString(Encoding.ASCII);
}
```

If you run this code and navigate to 127.0.0.1:8080 with chrome then `request` and `req` will start with 
`T / HTTP/1.1\r\nHost: 127.0.0.1:8080\r\nConnection: keep-alive\r\n`
instead of 
`GET / HTTP/1.1\r\nHost: 127.0.0.1:8080\r\nConnection: keep-alive\r\n`
This is not about string, byte[] Data has 2 bytes less than it should.

**Comment by Job79** [comment]
Hello @ZigmundL,

Currently you are using the default framing of EasyTcp.
This is Tcp.PrefixLengthProtocol, which determines the length of every incoming message by the value of its first 2 bytes.

What you need is Tcp.NoneProtocol, this protocol doesn't implement any kind of framing.
[Take a look here for the difference between protocols](https://github.com/Job79/EasyTcp/blob/master/EasyTcp3/EasyTcp3.Examples/Protocols/ProtocolsExample.cs)

And here is your code with Tcp.NoneProtocol:
```cs
        static async Task Main(string[] args)
        {
            using var server = new EasyTcpServer(new NoneProtocol()).Start(8080);
            server.OnDataReceive += Server_OnDataReceive;
            await Task.Delay(-1); // Infinite wait
        }

        private static void Server_OnDataReceive(object sender, Message e)
        {
            string request = e.ToString(Encoding.ASCII);
            Console.WriteLine(request);
        }
```

Note that NoneProtocol has  a default max data size of 1024 bytes. This can be changed by passing a new buffersize to the NoneProtocol constructor.
Example: `new NoneProtocol(10240)`

**Comment by ZigmundL** [comment]
Thank you, works as expected. Very glad I can limit buffer, this is very helpful as defending mechanism. This a bit confusing, because I was expected it to work like this OutOfTheBox when I installed package from NuGet. Anyway, Thanks.

Is this server works fine with a lot of connections? https://en.wikipedia.org/wiki/C10k_problem

**Comment by Job79** [comment]
Server should be fine with many connections, but the `.Start()` function on the server is limited to 65536(- used ports by other application) connections.
But this would be more then enough for most use cases.

When needing more connections, create your own socket, bind it to some IP's and call the start function with the socket as parameter.

[See also this page](https://serverfault.com/questions/160996/more-than-65536-tcp-connections-on-linux)
