### ISSUE TITLE
EasyTcpClient to EasyTCPClientAction

### ISSUE THREAD

**Issue by yoyomax80400** [Job79/EasyTcp#48]
Hi,
Thanks for shared this easy library for TCP.
He is possible to get a EasyTCPClientAction ? like server does ...

thanks

**Comment by Job79** [comment]
Hello @yoyomax80400,
do you mean a client version of the EasyTcpActionServer?
This is already included and is named [EasyTcpActionClient](https://github.com/Job79/EasyTcp/blob/master/EasyTcp3/EasyTcp3.Actions/EasyTcpActionClient.cs), it works exactly the same as the EasyTcpActionServer.

**Comment by yoyomax80400** [comment]
Sorry .. Thanks so much for answer
