### ISSUE TITLE
How to find remoteEndPoint in OnDataReceive event 

### ISSUE THREAD

**Issue by tientuphudu** [Job79/EasyTcp#50]
is there missing method to know remoteEndPoint  on  OnDataReceive event?
`    server.OnDataReceive += (sender, message) =>{
remoteEndPoint  ?
}`

**Comment by Job79** [comment]
The message class contains the EasyTcpClient. (sender)
This example explains it:
```cs
using var server = new EasyTcpServer().Start(8080);
server.OnDataReceive += (sender, message) =>
{
     EasyTcpClient client = message.Client; // Sender 
     Socket socket = client.BaseSocket; // Socket of sender
};
```

**Comment by tientuphudu** [comment]
thank you!
So why dont we use 
`client.GetEndPoint().Address.ToString()
client.GetEndPoint().Port.ToString()

`
