### ISSUE TITLE
can we run on old .netframework version? 

### ISSUE THREAD

**Issue by tientuphudu** [Job79/EasyTcp#51]
HI @Job79 . 
I have a question about compatible user client. 
They always use old system that only using .netframework 4.0, or 4.5
Can we low down requirement about this library and EasyEncypt library ?
Now this only running in netframework 4.7+ 
So many user can't run this deployed app

**Comment by Job79** [comment]
Hello @tientuphudu,

This would be great but unfortunately I can't compile any .net framework version on my linux machine.
You could try re-compiling the library yourself, but there is a possibility that it isn't compatible. 

.net framework 1.3 is supported,[ which supports .net framework 4.6+](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
Support for <4.5.1 [ended on January 12, 2016.](https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework) So I think its unlikely that many people are still using this version.
