### ISSUE TITLE
Stop Server

### ISSUE THREAD

**Issue by bnaambo** [Job79/EasyTcp#54]
is it possible to stop the server without closing the console or winform?

**Comment by Job79** [comment]
Hello @bnaambo,

Stopping the server is done by disposing the server. 
Here is an example:
```cs
        static async Task Main(string[] args)
        {
            var server = new EasyTcpServer().Start(8080); // Create server
            server.OnDataReceive += (s, message) => Console.WriteLine(message);
            
            await Task.Delay(10000); // Wait 10 seconds
            server.Dispose(); // Stop server
        }
```

Disposing the server will destroy the server, it is currently not possible to call `.start()` again.

**Comment by bnaambo** [comment]
thanks, so curently not possible to include it in a guy with start stop button and then start it again.

**Comment by Job79** [comment]
> thanks, so curently not possible to include it in a guy with start stop button and then start it again.

Start/Stop would be possible by creating a whole new server. 
Here is an example:
```cs
public static EasyTcpServer Server;
        
static async Task Main(string[] args)
{
    Start();
    await Task.Delay(1000); // Wait 10 seconds
    Stop();
            
    Start(); // Restart server
    Console.ReadLine();
}

static void Start()
{
    Server = new EasyTcpServer().Start(8079); // Reassign and Create server
    Server.OnDataReceive += (s, message) => Console.WriteLine(message); 
}

static void Stop()
{
    Server.Dispose();
}
```

**Comment by bnaambo** [comment]
thx will try it :)

**Comment by bnaambo** [comment]
this worked thanks
