### ISSUE TITLE
Exceed 64K limit packet size?

### ISSUE THREAD

**Issue by cristianszpisjak** [Job79/EasyTcp#57]
Hello.

I use EasyTcpServer with .NET Core console and Topshelf to install it as a Windows Service.
I face the problem with the size of the package exceeding 64k and I get an overflow exception. I need to mention that I have no control over the client implementation.

My code looks like:
`this.TCPServer = new EasyTcpServer(new EasyTcp3.Protocols.Tcp.DelimiterProtocol("\x004", autoAddDelimiter: false, autoRemoveDelimiter: false, encoding: Encoding.UTF8));`
`this.TCPServer.OnDataReceive += TCPServer_OnDataReceive;`

And on the receive event I have something like:
`var DataReceived = e.ToString();`

Is there a way to configure the library to support large amount of data in this scenario?
Thank you.

**Comment by Job79** [comment]
Hello,

Thanks for bringing this to my attention, is seems like there is a problem with the DelimiterProtocol (& DefaultTcpProtocol). It should be able to handle much larger data packets. 

It seems like DefaultTcpProtocol/OnReceiveCallback and DefautTcpProtocol/EnsureDataReceiverIsRunning are filling the stack with method calls when using the DelimiterProtocol. I will try to fix this and add my changes to the develop branch.

A solution would be using the LargeArrayUtil or the StreamUtil for large data. But this would require the receiver to know the length of the message. This would be the best solution, and would also be much faster then letting DelimiterProtocol do all the work.

**Comment by cristianszpisjak** [comment]
Hello.

Thank you for the fast response.
I'm using the library in a production environment where multiple machines are sending data across the network. The big issue I'm facing is that I don't have access to those machines software implementation and also the data sent varies from 1KB to 100KB with each transmission, so it's impossible for me to predict the size.

I hoped this is just a bug with the library and can be solved and if you say you could fix it, I'll very much appreciate it.

Cheers.

**Comment by Job79** [comment]
Hello,

I just pushed a solution for this bug to the develop branch. ([c2f31a794502e5033fb9213e5dad5556dcb60f0f](https://github.com/Job79/EasyTcp/commit/c2f31a794502e5033fb9213e5dad5556dcb60f0f))
This should solve the problem, but it might take some time before I publish an updated version to nuget. Here is a .nupkg: [Release.zip](https://github.com/Job79/EasyTcp/files/5541319/Release.zip), or clone, go to develop and build the repo.

Hope this helps your project, I will close this issue once you confirm and I published a new nuget package.

**Comment by cristianszpisjak** [comment]
Hi,

I did some initial tests but didn't fully tested the modification.
I will run a fully test the next week and coming back to you with the results.

Thank you.

**Comment by cristianszpisjak** [comment]
Hello,

I did a couple of tests and it seems that for now at least, is sending all the data correctly without throwing the overflow exception.
I think you can push the modification to the release branch and if I will see this behavior in the future I will write you again.

Thank you for the support.

**Comment by Job79** [comment]
Fixed in EasyTcp4.0.0-beta

**Comment by cristianszpisjak** [comment]
Hello,

If you're using the EasyTcp4.0.0-beta version from nuget.org this bug reappears.
The previous local nuget you sent me is working fine but the beta version still has that bug.

Thank you.
