### ISSUE TITLE
Possibility to disconnect a Client from server side in Code?

### ISSUE THREAD

**Issue by bnaambo** [Job79/EasyTcp#59]
Is it possible do disconnect a client from the servers side? in the server Code?

**Comment by cristianszpisjak** [comment]
Hello,

I'm using the code below on the `OnDataReceived` event to disconnect the client:

`// Disconnect client`
`e.Client.Dispose();`

**Comment by bnaambo** [comment]
I like to use that on OnConnect to automatically disconnect if the connected clients are more then a preset int
`internal static readonly int maxClients = 1;`

**Comment by Job79** [comment]
Hi,

Just call .Dispose() on the client like @cristianszpisjak suggested.
Here is an example for the OnConnect event:
```cs
using EasyTcp3;
using EasyTcp3.ServerUtils;

var server = new EasyTcpServer().Start(8080);

server.OnConnect += (sender, client) =>
{
    if (((EasyTcpServer)sender).ConnectedClientsCount > 10)
        client.Dispose(); // Disconnect client
};
```

Note that the OnConnect() function will return true client side, because the client is accepted(the event is fired) and then disconnected(`.Dispose()`).

**Comment by bnaambo** [comment]
thx worked great
