### ISSUE TITLE
PrefixLengthProtocol filling Message.Data with null/empty data

### ISSUE THREAD

**Issue by aiaf** [Job79/EasyTcp#64]
Client: PHP 7.4 on Ubuntu 20.04.1 LTS, Amazon EC2.

Can confirm that when the request is around 3KB,  framing fails and OnDataReceive is fired at least twice. The first Message.Data is the correct content *length*, but actual real content is only around 78%, the remaining 22% is empty/null and when converted using .ToString() is turned into white space. The 2nd invocation of OnDataReceive creates a Message.Data that's around 16KB that contains the remaining data from the original request (minus a couple of bytes in the beginning) and a whole lot of white space. Client.EndPoint is identical in both OnDataReceive.  In my client code, the socket is written to only once, and the number of written bytes is the correct length (~3kb). Requests smaller than 3kb don't seem to exhibit these bugs.

The same code works fine when the client is on a macOS. I've switched to DelimiterProtocol since which works more reliably.

**Comment by Job79** [comment]
Hello,

Thanks for creating an issue. I rewrote the PrefixLengthProtocol and published a new version to nuget (EasyTcp4.0.0-beta)
I wrote some tests to reproduce this issue and it looks like I fixed this problem when adding support for larger packages to the PrefixLengthProtocol.
Could you try the newest version and report back if the issue is resolved?

**Comment by aiaf** [comment]
Thanks for the fast response, @Job79!

Unfortunately, got an unhandled OutOfMemoryException using EasyTCP4 and this code:

`using var server = new EasyTcpServer(new PrefixLengthProtocol(65535 * 7)).Start((ushort)Settings.ListenPort);`

Otherwise, my code has not changed. I'm using netcoreapp2.2 (necessary) on Windows Server 2008 R2 if that helps.

**Comment by Job79** [comment]
Hi,

Could you share some more information?
I couldn't reproduce the the OutOfMemoryException, tried with netcoreapp2.2 & net5.0 on alpine and arch.
Is it possible that your machine runs out of memory when starting the server? This would give an OutOfMemoryException.

**Comment by Job79** [comment]
Can't reproduce this issue, please reopen if still valid
