### ISSUE TITLE
No "Send"-Method avaiable. :(

### ISSUE THREAD

**Issue by SonOfKorriban** [Job79/EasyTcp#65]
Greetings from germany,
i was using your EasyTcp NuGet Package 2.0.4.2 for my current project, before i was forced to change my target framework to .NET Framework. So i now use your newest Version of EasyTcp, Version 3.7.8.
Well, i enjoyed really the "server.Send(Socket client, byte[] data)" Method in the Server-Class for sending Data zu specific Clients.

Why did you removed that feature? Or do you have still implemented it somewhere else? My Application has got a chat function. If i use "SendAll" i have to check on each client, if this message is avaiable for it. That would be not as elegant as your "Send" Method.

Anyway, THANK YOU for creating this Package, but can u help me with this one?

EDIT: I tried to install EasyTcp.Actions, but i get this error:
"EasyTcp 3.7.8' is not compatible with 'EasyTcp.Actions 4.0.0 Restriction: EasyTcp (>= 4.0.0-beta)'.
But there is no EasyTcp 4.0.0 Beta...

EDIT2: i finally got an earlier Version of EasyTcp.Actions and have noticed the cool new feature with SendAction. But still no Method for Sending expecially to ONE client :(

**Comment by Job79** [comment]
The `EasyTcpServer.Send(Socket client, byte[] data)` function is replaced by `EasyTcpClient.Send(byte[] data)`

All server events have an EasyTcpClient (or message with a client) as parameter, so to send data to 1 client just use `client.Send(data)` or `message.Client.Send(data)`

```cs
using EasyTcp4;
using EasyTcp4.ServerUtils;
using EasyTcp4.ServerUtils;

using var server = new EasyTcpServer().Start(8080);
server.OnConnect += (sender, client) => client.Send("reply to sender");
server.OnDataReceive += (sender, message) => message.Client.Send("reply to sender");
```

Looks like i used a wrong version while publishing EasyTcp.Actions, thanks for bringing this to my attention.

**Comment by SonOfKorriban** [comment]
Thank you very much for responsing! Helped me a lot!
