### ISSUE TITLE
PrefixLengthProtocol in v4.x is is not compatible with itself depending on max message size

### ISSUE THREAD

**Issue by DomasM** [Job79/EasyTcp#67]
Prior to version 4.x PrefixLengthProtocol used just two bytes to encode message length which was limited to 65535 bytes. Since version 4.x header length is chosen based on max message length, which means that clients and server must be strictly versioned together. Furthermore, I am not even sure if it is clear  for new users that changing max message length from say 50000 to 100000 bytes will likely break things. So I suggest to have just one version with of PrefixLengthProtocol  which always uses four bytes to encode message length, as two byte overhead is such small and insignificant. For users migrating from 3.x  which might need to have backward compatibility there could be special static method to create such instance or just different obsolete class.

**Comment by Job79** [comment]
25470c3b1629fe9e25bdac2ad1d1a041eb07caa9
