### ISSUE TITLE
Exceed 64K limit packet size?

### ISSUE THREAD

**Issue by cristianszpisjak** [Job79/EasyTcp#68]
Hello,

If you're using the EasyTcp4.0.0-beta version from nuget.org the problem with the size of the package exceeding 64k reappears.
The previous local nuget you sent me is working fine but the beta version still has that bug.

Thank you.

**Comment by Job79** [comment]
More information on bug: #57 
Will look into it when I have some time. [Unit test](https://github.com/Job79/EasyTcp/blob/develop/EasyTcp4/EasyTcp4.Test/EasyTcp/DataTransfer/Protocols/PrefixLength.cs) seems to be fine.

**Comment by Job79** [comment]
Seems there is no unit test for the delimiter and plainTcp protocol.
Will add those and see if there are problems.
