### ISSUE TITLE
MemoryStreams created in Encryption.Decrypt() are not disposed

### ISSUE THREAD

**Issue by Kermalis** [Job79/EasyTcp#7]
Issue here: https://github.com/GHenkje/EasyTcp/blob/master/EasyTcp/Encryption.cs#L153

A more optimized approach is to use the following instead:
```cs
byte[] ret = new byte[byteCount];
Buffer.BlockCopy(Decrypted, 0, ret, 0, byteCount);
return ret;
```

**Comment by Job79** [comment]
Encryption is removed in 3.0 (for now) so this is no longer an problem.
