### ISSUE TITLE
Client disconnecting issue

### ISSUE THREAD

**Issue by cosmin-90** [Job79/EasyTcp#76]
Hello, 
First of all i really like this project and i hope it will be maintained as long as possible.
I tried to implement this extension in my project, witch sends and receives alot of packets, but i experienced some client disconnecting issues.
After some digging i managed to isolate the issue and make a simple example witch reproduce the issue (see the code below).

```using EasyTcp4;
using EasyTcp4.ClientUtils;
using EasyTcp4.Protocols.Tcp;
using EasyTcp4.ServerUtils;
using System;
using System.Diagnostics;

namespace eTCPTest
{
    internal class Program
    {
       static EasyTcpServer server;
       static EasyTcpClient client;
        static void Main(string[] args)
        {
            //server
            server = new EasyTcpServer();
            server.Protocol = new PlainTcpProtocol(1024);
            server.Start(888);
            server.OnDataReceive += Server_OnDataReceive; //We subscribe to this event to send echo replies to simulate some traffic

            //client
            client = new EasyTcpClient();
            client.Protocol = new PlainTcpProtocol(1024);

            if (client.Connect("127.0.0.1", 888)) //Making sure we are connected to server
            {
                int NotConnectedCounter = 0;
                int ConnectedCounter = 0;
                for (int i = 0; i < 1000000; i++)
                {
                    if (client.IsConnected())
                    {
                        client.Send("AAA");
                        ConnectedCounter++;
                    }
                    else
                    {
                        NotConnectedCounter += 1;
                    }
                }
                Console.WriteLine("Not Connected Count:" + NotConnectedCounter.ToString() + "\r\nConnected Count:" + ConnectedCounter.ToString());
            }
            else
            {
                Console.WriteLine("Cannot connect");
            }
        }

        private static void Server_OnDataReceive(object sender, Message e)
        {
            server.SendAll(e.Data); //echo reply
        }

    }
}
```
Normal output should be: Not Connected Count: 0 Connected Count: 1000000
But here's some actual ouputs: 
Not Connected Count: 999353 Connected Count: 647
Not Connected Count: 999485 Connected Count: 515
Not Connected Count: 999372 Connected Count: 628
Not Connected Count: 999313 Connected Count: 687

For the most of the time client.IsConnected() returns False, and it actually disconnects from the server.
If i remove the connection check it works just fine.
Also if we unsubscribe from OnDataReceived (to disable the echo replies) also works just fine.
Maybe i'm doing something wrong.

**Comment by Job79** [comment]
Thanks for reporting the bug, it should be fixed with 0827f1df211bced08a0293f3231e9443370e08c3

**Comment by Job79** [comment]
Update should be available when nuget accepts the upload, version will be 4.0.2

**Comment by cosmin-90** [comment]
> Update should be available when nuget accepts the upload, version will be 4.0.2

Nice, Thank you! :)
