### ISSUE TITLE
EasyTcpClient.SendAndGetReply() does not unsubscribe event if timeout occurs

### ISSUE THREAD

**Issue by Kermalis** [Job79/EasyTcp#8]
Here: https://github.com/GHenkje/EasyTcp/blob/master/EasyTcp/Client/EasyTcpClient.cs#L470

If the timeout were to occur, `reply` would be returned as null, but the event is not unsubscribed. If the message were to be received after this method already returned, the event handler will also throw an `ObjectDisposedException` at `signal.Set();`, which may crash the program unexpectedly with little debug info.

Even if no message is received, `signal` and `reply` (as well as the event handler) are prevented from being garbage collected, meaning you have a very small memory leak if the timeout occurs.

**Comment by Job79** [comment]
Fixed in 3.0
