### ISSUE TITLE
set time out for client to disconnect from server

### ISSUE THREAD

**Issue by mzelecom** [Job79/EasyTcp#80]
Hi.
how can i set client idle time out .
i need to auto disconnect client from sever if no data received from clients for 5 minutes.
does easytcp has this feature?
thanks

**Comment by Job79** [comment]
This feature is not implemented in EasyTcp, and I don't think it is something the library should handle.
It is possible to implement this outside of the library by embedding a timestamp in the client state, updating it when the server receives data, and creating a timer that loops through all the connected clients and disconnects clients with an old timestamp.

EasyTcp does have keep alive support however, and this is probably what most users want. It sends a heartbeat every x seconds to confirm that the connection is still open.
